name: Deployment Workflow

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'

      - name: Install all the dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY_PAIR }} 
          source: ./
          target: /home/ec2-user/app

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY_PAIR }}  
          script: |
            # Application deployment..
            cd /home/ec2-user/app

            sudo yum install python3 -y
            python3 -m pip --version

            # Virtual environment
            python -m venv venv
            source venv/bin/activate

            # Install dependencies
            pip install --upgrade pip
            pip install -r requirements.txt

            # Install nginx
            sudo yum update -y
            sudo yum install nginx -y
            sudo mkdir -p /etc/nginx

            # Copy nginx config and restart nginx
            sudo cp ./nginx/nginx.conf /etc/nginx/nginx.conf
            sudo systemctl start nginx
            sudo systemctl enable nginx

            # Start application server
            pkill -f "uvicorn main:app"  || echo "No running Uvicorn process found"
            echo "Starting application.."
            nohup venv/bin/uvicorn main:app --host 0.0.0.0 --port 8000 > app.log 2>&1 &

            echo Application logs
            tail -n 20 app.log
