name: Deployment Workflow

on: 
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Setup application
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'

      - name: Install all the dependencies from requirements
        run: |
          # Setup virtual environment
          python -m venv venv
          source venv/bin/activate

          # Install dependencies
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Copy nginx configuration and test
        run: |
          echo "Copying nginx configuration.."

          sudo cp ./nginx/nginx.conf /etc/nginx/nginx.conf
          sudo nginx -t

      - name: Restart Nginx
        run: |
          echo "Restarting Nginx.."

          sudo systemctl restart nginx

      - name: Deploy application
        run: |
          echo "Application deploying.."
          source venv/bin/activate

          # start your application
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 > uvicorn.log 2>&1 &

          echo "Application deployed.."
