name: Test Workflow

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Setup application
        uses: actions/setup-python@v3
        with:
          python-version: '3.12.3'

      - name: Install dependencies from requirements
        run: |
          # Setup virtual environment
          python -m venv venv
          . venv/bin/activate

          # Install dependencies
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests via pytest
        run: |
          . venv/bin/activate
          pytest